### ISSUE TITLE
While using allure-commandline via npm, an error getting displayed

### ISSUE THREAD

**Issue by anarwal** [allure-framework/allure-npm#1]
C:\Users\anarwal\IdeaProjects\cm-ui-automation>allure help
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\anarwal\AppData\Roaming\npm\node_modules\allure-commandline\dist\bin\allure
 ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by immo-huneke-zuhlke** [comment]
I think this might be the cause of an error I have just reported as an issue against mocha-allure-reporter. See https://github.com/allure-framework/mocha-allure-reporter/issues/16

**Comment by just-boris** [comment]
@anarwal sorry for a long response. Didn't get a notification about it.

Since that, I released new version `1.4.23`. It also has some fixes for Windows. Maybe it helps you.

**Comment by baev** [comment]
closed due to no response
