### ISSUE TITLE
Documentation - how to use?

### ISSUE THREAD

**Issue by thim81** [allure-framework/allure-npm#3]
Hi,

We have very simple junitreports.
But it's not clear how I can use the allureCommand line to generate a nice looking Allure report from it? Most documentation I find is based on the maven implementation.

Example:
```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
<testsuite name="Frisby Test: API: Validate non existing coupon" errors="0" tests="1" failures="1" time="0.228" timestamp="2016-11-17T17:15:15">
  <testcase classname="Frisby Test: API: Validate non existing coupon" name="
	[ POST https://app-dev.parcify.it/api/v3.0/parcel/validate/coupon ]" time="0.223"><failure type="expect" message="Expected 200 to equal 404.">Error: Expected 200 to equal 404.
    at new jasmine.ExpectationResult (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:114:32)
    at null.toEqual (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1316:29)
    at null.&amp;lt;anonymous&amp;gt; (/Users/tim/Sites/parcify/Q-Bert/node_modules/frisby/lib/frisby.js:493:42)
    at null.&amp;lt;anonymous&amp;gt; (/Users/tim/Sites/parcify/Q-Bert/node_modules/frisby/lib/frisby.js:1074:43)
    at jasmine.Block.execute (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:1145:17)
    at jasmine.Queue.next_ (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2177:31)
    at onComplete (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2173:18)
    at jasmine.WaitsForBlock.execute (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2659:5)
    at null._onTimeout (/Users/tim/Sites/parcify/Q-Bert/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js:2673:12)
    at Timer.listOnTimeout (timers.js:92:15)</failure></testcase>
</testsuite>
</testsuites>
```

**Comment by just-boris** [comment]
This repo only provides NPM-module for Allure.

To understand what is Allure and how it works, you need to start exploring from the core repository: https://github.com/allure-framework/allure-core

Also, it is important to mention, that Allure doesn't support Junit-xml, instead, it generates its own format. To receive this XML from your test result, you need to use adapter for your test framework, that you can find in the list here: https://github.com/allure-framework/allure-core/wiki
